---
- name: Configure all homelab hosts
  hosts: all
  roles:
    - common

- name: Install K3S on Kubernetes nodes
  hosts: gitlab
  roles:
    - kubes

- name: Install Gitea on Kubernetes nodes
  hosts: gitlab
  roles:
    - gitea
